// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TourGuideServer.Data;

#nullable disable

namespace TourGuideServer.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TourGuideServer.Models.Language", b =>
                {
                    b.Property<string>("LanguageCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LanguageName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LanguageCode");

                    b.ToTable("Languages");
                });

            modelBuilder.Entity("TourGuideServer.Models.POI", b =>
                {
                    b.Property<int>("POIID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("POIID"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("decimal(9,6)");

                    b.Property<int?>("OwnerID")
                        .HasColumnType("int");

                    b.Property<string>("RestaurantName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("POIID");

                    b.ToTable("POI", (string)null);
                });

            modelBuilder.Entity("TourGuideServer.Models.POITranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NarrationText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("POIID")
                        .HasColumnType("int");

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LanguageCode");

                    b.HasIndex("POIID", "LanguageCode")
                        .IsUnique();

                    b.ToTable("POI_Translations", (string)null);
                });

            modelBuilder.Entity("TourGuideServer.Models.QRCode", b =>
                {
                    b.Property<int>("QRID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QRID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("POIID")
                        .HasColumnType("int");

                    b.Property<string>("QRValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("QRID");

                    b.HasIndex("POIID");

                    b.HasIndex("QRValue")
                        .IsUnique();

                    b.ToTable("QRCode", (string)null);
                });

            modelBuilder.Entity("TourGuideServer.Models.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TourGuideServer.Models.VisitHistory", b =>
                {
                    b.Property<int>("VisitID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VisitID"));

                    b.Property<string>("LanguageUsed")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("POIID")
                        .HasColumnType("int");

                    b.Property<string>("ScanMethod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserID")
                        .HasColumnType("int");

                    b.Property<decimal?>("UserLat")
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal?>("UserLon")
                        .HasColumnType("decimal(9,6)");

                    b.Property<DateTime>("VisitTime")
                        .HasColumnType("datetime2");

                    b.HasKey("VisitID");

                    b.HasIndex("POIID");

                    b.HasIndex("UserID");

                    b.ToTable("VisitHistory", (string)null);
                });

            modelBuilder.Entity("TourGuideServer.Models.POITranslation", b =>
                {
                    b.HasOne("TourGuideServer.Models.Language", null)
                        .WithMany()
                        .HasForeignKey("LanguageCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TourGuideServer.Models.POI", null)
                        .WithMany("Translations")
                        .HasForeignKey("POIID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TourGuideServer.Models.QRCode", b =>
                {
                    b.HasOne("TourGuideServer.Models.POI", "POI")
                        .WithMany()
                        .HasForeignKey("POIID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("POI");
                });

            modelBuilder.Entity("TourGuideServer.Models.VisitHistory", b =>
                {
                    b.HasOne("TourGuideServer.Models.POI", "POI")
                        .WithMany()
                        .HasForeignKey("POIID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TourGuideServer.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID");

                    b.Navigation("POI");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TourGuideServer.Models.POI", b =>
                {
                    b.Navigation("Translations");
                });
#pragma warning restore 612, 618
        }
    }
}
